# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
orbs:
  coveralls: coveralls/coveralls@2.1.0
  browser-tools: circleci/browser-tools@1.4.1
jobs:
  run_tests:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: circleci/python:3.9.7-browsers
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

      - run:
          name: Install python dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run App
          command: python app/app.py &
      - run:
          name: Automated Unit Testing
          command: python -m pytest app/test_cases.py
      - run:
          name: Coveralls
          command: coverage run -m pytest app/
      - run:
          name: Report
          command: coverage report
      - run: 
          name: Get full html report
          command: coverage html
      - run:
          name: Terminate app
          command: killall python

      - store_artifacts:
          path: htmlcov

  # Orchestrate jobs using workflows
  # See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build_test:
    jobs:
      - run_tests
